# Generated by Django 5.2.4 on 2025-07-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_addad',
            new_name='date_added',
        ),
    ]
